import PdtPisotBoundary

/-!
# Hamiltonian boundary of a complex arithmetic tick

A nonzero complex multiplier splits into a positive radial factor and a
unit-modulus phase.  The phase is generated by real scalar Hamiltonians, with
the complete logarithm-branch ambiguity classified by integers.  A raw
multiplier whose norm differs from one cannot be generated by any real scalar
Hamiltonian.

The cubic and quartic bounds then put the NON-REAL CONJUGATES of the two
polynomials on opposite sides of the radial boundary — those of `x³ − x − 1`
inside the unit circle, those of `x⁴ − x − 1` outside — while placing both raw
ticks outside scalar Hermitian evolution.  (Each polynomial has a real root
greater than one, so the real roots do not separate the two cases; the conjugate
pair does.  The quartic also has a second, negative real root, which the radial
statement does not concern.)  These are
mathematical statements about one complex mode.  They do not choose a physical
tick duration, logarithm branch, observable algebra, or open-system dynamics,
and they do not turn the opposite radial directions into a physical arrow of
time or derive any physical Hamiltonian.
-/

namespace PDT.HamiltonianBoundary

noncomputable section

/-- The unit-modulus phase in the polar decomposition of a complex tick. -/
def unitaryPhase (σ : ℂ) : ℂ :=
  Complex.exp ((Complex.arg σ : ℂ) * Complex.I)

/-- Evolution for one scalar Hermitian mode with real energy `h` over duration
`dt`, in units where `ℏ = 1`. -/
def scalarEvolution (h dt : ℝ) : ℂ :=
  Complex.exp ((-(h * dt) : ℂ) * Complex.I)

/-- The integer logarithm branches which generate the same normalized phase. -/
def scalarHamiltonian (σ : ℂ) (dt : ℝ) (k : ℤ) : ℝ :=
  (2 * Real.pi * (k : ℝ) - Complex.arg σ) / dt

/-- Exact radial-times-phase polar decomposition. -/
theorem radial_phase_decomposition (σ : ℂ) :
    (‖σ‖ : ℂ) * unitaryPhase σ = σ := by
  exact Complex.norm_mul_exp_arg_mul_I σ

/-- The normalized phase lies on the unit circle. -/
theorem unitaryPhase_norm (σ : ℂ) : ‖unitaryPhase σ‖ = 1 := by
  exact Complex.norm_exp_ofReal_mul_I (Complex.arg σ)

/-- For a nonzero tick, the phase is exactly the tick divided by its norm. -/
theorem unitaryPhase_eq_div_norm {σ : ℂ} (hσ : σ ≠ 0) :
    unitaryPhase σ = σ / (‖σ‖ : ℂ) := by
  have hn : (‖σ‖ : ℂ) ≠ 0 := by
    exact_mod_cast (norm_ne_zero_iff.mpr hσ)
  apply (eq_div_iff hn).2
  simpa [mul_comm] using radial_phase_decomposition σ

/-- Every real scalar Hamiltonian evolution has unit norm. -/
theorem scalarEvolution_norm (h dt : ℝ) : ‖scalarEvolution h dt‖ = 1 := by
  rw [scalarEvolution, Complex.norm_exp]
  simp

/-- A raw gain or loss multiplier cannot be one-step evolution from a real
scalar Hamiltonian. -/
theorem no_scalarHamiltonian_for_raw_tick {σ : ℂ} (hnorm : ‖σ‖ ≠ 1)
    (dt : ℝ) : ¬ ∃ h : ℝ, scalarEvolution h dt = σ := by
  rintro ⟨h, heq⟩
  apply hnorm
  rw [← heq]
  exact scalarEvolution_norm h dt

/-- Every integer branch generates the normalized phase over a positive tick
duration. -/
theorem scalarHamiltonian_generates_phase (σ : ℂ) {dt : ℝ} (hdt : 0 < dt)
    (k : ℤ) : scalarEvolution (scalarHamiltonian σ dt k) dt = unitaryPhase σ := by
  have hdt0 : dt ≠ 0 := ne_of_gt hdt
  unfold scalarEvolution scalarHamiltonian unitaryPhase
  have hreal : -(((2 * Real.pi * (k : ℝ) - Complex.arg σ) / dt) * dt) =
      Complex.arg σ - 2 * Real.pi * (k : ℝ) := by
    field_simp
    ring
  have hcomplex :
      -(↑((2 * Real.pi * (k : ℝ) - Complex.arg σ) / dt) * ↑dt : ℂ) =
        ((Complex.arg σ - 2 * Real.pi * (k : ℝ) : ℝ) : ℂ) := by
    exact_mod_cast hreal
  rw [hcomplex]
  apply Complex.exp_eq_exp_iff_exists_int.mpr
  refine ⟨-k, ?_⟩
  push_cast
  ring

/-- Complete scalar classification: the real Hamiltonians giving the
normalized phase are exactly the integer logarithm branches. -/
theorem scalarEvolution_eq_phase_iff (σ : ℂ) {dt : ℝ} (hdt : 0 < dt) (h : ℝ) :
    scalarEvolution h dt = unitaryPhase σ ↔
      ∃ k : ℤ, h = scalarHamiltonian σ dt k := by
  have hdt0 : dt ≠ 0 := ne_of_gt hdt
  constructor
  · intro heq
    unfold scalarEvolution unitaryPhase at heq
    obtain ⟨n, hn⟩ := Complex.exp_eq_exp_iff_exists_int.mp heq
    refine ⟨-n, ?_⟩
    unfold scalarHamiltonian
    have hI :
        -(↑h * ↑dt) * Complex.I =
          ((Complex.arg σ + (n : ℝ) * (2 * Real.pi) : ℝ) : ℂ) * Complex.I := by
      rw [hn]
      push_cast
      ring
    have hreal : -(h * dt) = Complex.arg σ + (n : ℝ) * (2 * Real.pi) := by
      have hcancel := mul_right_cancel₀ Complex.I_ne_zero hI
      exact_mod_cast hcancel
    apply (eq_div_iff hdt0).2
    push_cast at hreal ⊢
    linarith
  · rintro ⟨k, rfl⟩
    exact scalarHamiltonian_generates_phase σ hdt k

/-- Distinct logarithm branches differ by the expected energy quantum. -/
theorem scalarHamiltonian_sub (σ : ℂ) {dt : ℝ} (hdt : 0 < dt) (k m : ℤ) :
    scalarHamiltonian σ dt k - scalarHamiltonian σ dt m =
      2 * Real.pi * ((k - m : ℤ) : ℝ) / dt := by
  have hdt0 : dt ≠ 0 := ne_of_gt hdt
  unfold scalarHamiltonian
  field_simp
  push_cast
  ring

/-- Both nonreal PDT conjugate ticks lie outside raw scalar Hermitian
evolution: the cubic contracts and the quartic expands. -/
theorem cubic_quartic_raw_ticks_not_scalarHamiltonian
    {z w : ℂ} (hz : z ^ 3 = z + 1) (hzim : z.im ≠ 0)
    (hw : w ^ 4 = w + 1) (hwim : w.im ≠ 0) (dt : ℝ) :
    (‖z‖ < 1 ∧ ¬ ∃ h : ℝ, scalarEvolution h dt = z) ∧
      (1 < ‖w‖ ∧ ¬ ∃ h : ℝ, scalarEvolution h dt = w) := by
  have hzlt := PDT.cubic_conj_norm_lt_one z hz hzim
  have hwgt := PDT.quartic_conj_norm_gt_one w hw hwim
  exact ⟨⟨hzlt, no_scalarHamiltonian_for_raw_tick (ne_of_lt hzlt) dt⟩,
    ⟨hwgt, no_scalarHamiltonian_for_raw_tick (ne_of_gt hwgt) dt⟩⟩

end
end PDT.HamiltonianBoundary

#print axioms PDT.HamiltonianBoundary.radial_phase_decomposition
#print axioms PDT.HamiltonianBoundary.unitaryPhase_norm
#print axioms PDT.HamiltonianBoundary.unitaryPhase_eq_div_norm
#print axioms PDT.HamiltonianBoundary.scalarEvolution_norm
#print axioms PDT.HamiltonianBoundary.no_scalarHamiltonian_for_raw_tick
#print axioms PDT.HamiltonianBoundary.scalarHamiltonian_generates_phase
#print axioms PDT.HamiltonianBoundary.scalarEvolution_eq_phase_iff
#print axioms PDT.HamiltonianBoundary.scalarHamiltonian_sub
#print axioms PDT.HamiltonianBoundary.cubic_quartic_raw_ticks_not_scalarHamiltonian
