/-
PdtMahlerBox — the certificate tables and the 6,171-element coverage
theorem for the θ = 139/100 box (see PdtMahler.lean for the soundness
layer). Split into its own module because the kernel check of
`boxD4_all` takes ~7 minutes; it builds once and is imported.
-/
import PdtMahler

namespace PDT
namespace Mahler

/-! ## Phase D2: the box, the certificate tables, and the coverage theorem -/

/-- The four minimizers: `x⁴−x−1` and its sign/reciprocal transforms. -/
def tieList : List Z4 := [(0, 0, -1, -1), (0, 0, 1, -1), (1, 0, 0, -1), (-1, 0, 0, -1)]

/-- The four degree-4 cyclotomic tuples: Φ₅, Φ₈, Φ₁₀, Φ₁₂. -/
def cycloList : List Z4 := [(1, 1, 1, 1), (0, 0, 0, 1), (-1, 1, -1, 1), (0, -1, 0, 1)]

/-- Product of a monic linear and a monic cubic, at tuple level:
`(x + u)(x³ + v₂x² + v₁x + v₀)`. -/
def mul13 (u : ℤ) (v : ℤ × ℤ × ℤ) : Z4 :=
  (v.1 + u, v.2.1 + u * v.1, v.2.2 + u * v.2.1, u * v.2.2)

/-- Product of two monic quadratics, at tuple level:
`(x² + a₁x + a₀)(x² + b₁x + b₀)`. -/
def mul22 (w1 w2 : ℤ × ℤ) : Z4 :=
  (w1.1 + w2.1, w1.2 + w2.2 + w1.1 * w2.1, w1.1 * w2.2 + w2.1 * w1.2, w1.2 * w2.2)

/-- Factor witnesses (linear × cubic) for the reducible box elements the
Graeffe certificate cannot kill (measure ≤ θ). Generated by the scoping
prototype; each entry is checked by kernel arithmetic in `boxD4_all`. -/
def facts13 : List (ℤ × (ℤ × ℤ × ℤ)) := [
  (-1, (-3, 3, -1)), (0, (-3, 3, -1)), (-1, (-2, 2, -1)), (1, (-3, 3, -1)),
  (-1, (-1, 0, 0)), (-1, (-1, 0, 1)), (-1, (-1, 1, -1)), (-1, (-1, 1, 0)),
  (-1, (0, -1, -1)), (0, (-1, -1, 1)), (-1, (0, -1, 1)), (-1, (0, 0, -1)),
  (-1, (0, 0, 0)), (-1, (0, 0, 1)), (0, (-1, 0, 1)), (-1, (0, 1, 0)),
  (0, (-1, 1, 0)), (-1, (1, -1, -1)), (0, (0, -1, -1)), (-1, (1, 0, -1)),
  (-1, (1, 0, 0)), (0, (0, -1, 1)), (1, (-1, 0, 1)), (-1, (1, 1, 0)),
  (-1, (1, 1, 1)), (0, (0, 0, 0)), (0, (0, 0, 1)), (0, (0, 1, 0)),
  (1, (0, -1, -1)), (-1, (2, 1, 0)), (1, (0, -1, 1)), (-1, (2, 2, 1)),
  (0, (1, 0, -1)), (1, (0, 0, 0)), (1, (0, 0, 1)), (0, (1, 1, 0)),
  (0, (1, 1, 1)), (-1, (3, 3, 1)), (1, (1, 0, -1)), (0, (2, 1, 0)),
  (0, (2, 2, 1)), (1, (1, 1, 1)), (0, (3, 3, 1)), (1, (2, 2, 1)),
  (1, (3, 3, 1))]

/-- Factor witnesses (quadratic × quadratic), same role as `facts13`. -/
def facts22 : List ((ℤ × ℤ) × (ℤ × ℤ)) := [
  ((-1, 1), (-1, 1)), ((-1, 1), (0, 1)), ((-1, 1), (1, 1)),
  ((0, 1), (0, 1)), ((0, 1), (1, 1)), ((1, 1), (1, 1))]

/-- Per-element certificate check: tie, cyclotomic, explicit factorization,
or an iterated Graeffe lower certificate at θ = 139/100. -/
def elemOK (t : Z4) : Bool :=
  decide (t ∈ tieList) || decide (t ∈ cycloList) ||
  facts13.any (fun p => decide (mul13 p.1 p.2 = t)) ||
  facts22.any (fun p => decide (mul22 p.1 p.2 = t)) ||
  lowerCert 9 139 100 t

/-- The coefficient box `B(139/100)`: `|a| ≤ 5, |b| ≤ 8, |c| ≤ 5, |e| ≤ 1`. -/
noncomputable def boxD4 : Finset Z4 :=
  (Finset.Icc (-5 : ℤ) 5) ×ˢ (Finset.Icc (-8 : ℤ) 8) ×ˢ
    (Finset.Icc (-5 : ℤ) 5) ×ˢ (Finset.Icc (-1 : ℤ) 1)

set_option maxRecDepth 100000
set_option maxHeartbeats 12000000

/-- COVERAGE: every element of the box carries a certificate. The finite
heart of the minimality theorem — 6,171 kernel-checked certificates. -/
theorem boxD4_all : ∀ t ∈ boxD4, elemOK t = true := by decide

set_option maxRecDepth 512
set_option maxHeartbeats 200000

end Mahler
end PDT
